name: Node.js CI

on:
    push:
        branches: [ main ]

    pull_request:
        branches: [ main ]

jobs:
    build-job:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: 14.x

        steps:
        - uses: actions/checkout@v4

        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v4
          with:
            node-version: ${{ matrix.node-version }}

        - name: Install dependencies
          run: |
            if [ -e yarn.lock ]; then
            yarn install --forzen-lockfile
            elif [ -e package-lock.json ]; then
            npm ci
            else
            npm i
            fi

        - run: npm ci

        - run: npm run build --if-present

        - run: npm test
